name: Build and test

on:
    - push
    - pull_request

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Install ubuntu packages to build
      run: |
          sudo apt-get install python3 python3-pip build-essential cmake ninja-build
          pip3 install poetry
    - name: ONNX Test Cases
      run: |
          poetry install
          poetry run pytest
